name: 'upload-release-asset'

description: 'Upload a release asset'
author: 'GitHub'
inputs:
  github-token:
    description: 'A token with permission to create and delete releases.  Generally secrets.GITHUB_TOKEN.'
    required: true
  upload-url:
    description: 'The URL for uploading assets to the release.  Can be taken from the outputs of an api call to create a release like in im-open/create-release.'
    required: true
  asset-path:
    description: 'The path to the asset you want to upload.'
    required: true
  asset-name:
    description: 'The name of the asset you want to upload.'
    required: true
  asset-content-type:
    description: 'The content-type of the asset you want to upload. See the supported Media Types here: https://www.iana.org/assignments/media-types/media-types.xhtml for more information.'
    required: true

outputs:
  asset-browser-download-url:
    description: 'URL users can navigate to in order to download the uploaded asset'
runs:
  using: 'node16'
  main: 'dist/index.js'
